package ltudjava.hcb.bt2.dto;
// Generated Aug 15, 2019 10:19:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name="grade"
    ,catalog="scoremanagement"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Grade  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<TimeTable> timeTables = new HashSet<TimeTable>(0);

    public Grade() {
    }

	
    public Grade(String name) {
        this.name = name;
    }
    public Grade(String name, Set<TimeTable> timeTables) {
       this.name = name;
       this.timeTables = timeTables;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false, length=8)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grade")
    public Set<TimeTable> getTimeTables() {
        return this.timeTables;
    }
    
    public void setTimeTables(Set<TimeTable> timeTables) {
        this.timeTables = timeTables;
    }




}


