package ltudjava.hcb.bt2.dto;
// Generated Aug 18, 2019 10:56:04 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Remarking generated by hbm2java
 */
@Entity
@Table(name="remarking"
    ,catalog="scoremanagement"
)
public class Remarking  implements java.io.Serializable {


     private RemarkingId id;
     private Float scoreOld;
     private Float scoreDesired;
     private String reason;
     private String status;

    public Remarking() {
    }

	
    public Remarking(RemarkingId id) {
        this.id = id;
    }
    public Remarking(RemarkingId id, Float scoreOld, Float scoreDesired, String reason, String status) {
       this.id = id;
       this.scoreOld = scoreOld;
       this.scoreDesired = scoreDesired;
       this.reason = reason;
       this.status = status;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="scoreId", column=@Column(name="score_id", nullable=false) ), 
        @AttributeOverride(name="scoreType", column=@Column(name="score_type", nullable=false, length=32) ) } )
    public RemarkingId getId() {
        return this.id;
    }
    
    public void setId(RemarkingId id) {
        this.id = id;
    }

    
    @Column(name="score_old", precision=12, scale=0)
    public Float getScoreOld() {
        return this.scoreOld;
    }
    
    public void setScoreOld(Float scoreOld) {
        this.scoreOld = scoreOld;
    }

    
    @Column(name="score_desired", precision=12, scale=0)
    public Float getScoreDesired() {
        return this.scoreDesired;
    }
    
    public void setScoreDesired(Float scoreDesired) {
        this.scoreDesired = scoreDesired;
    }

    
    @Column(name="reason", length=512)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    
    @Column(name="status", length=32)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


