package ltudjava.hcb.bt2.dto;
// Generated Aug 18, 2019 10:56:04 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RemarkingId generated by hbm2java
 */
@Embeddable
public class RemarkingId  implements java.io.Serializable {


     private int scoreId;
     private String scoreType;

    public RemarkingId() {
    }

    public RemarkingId(int scoreId, String scoreType) {
       this.scoreId = scoreId;
       this.scoreType = scoreType;
    }
   


    @Column(name="score_id", nullable=false)
    public int getScoreId() {
        return this.scoreId;
    }
    
    public void setScoreId(int scoreId) {
        this.scoreId = scoreId;
    }


    @Column(name="score_type", nullable=false, length=32)
    public String getScoreType() {
        return this.scoreType;
    }
    
    public void setScoreType(String scoreType) {
        this.scoreType = scoreType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RemarkingId) ) return false;
		 RemarkingId castOther = ( RemarkingId ) other; 
         
		 return (this.getScoreId()==castOther.getScoreId())
 && ( (this.getScoreType()==castOther.getScoreType()) || ( this.getScoreType()!=null && castOther.getScoreType()!=null && this.getScoreType().equals(castOther.getScoreType()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getScoreId();
         result = 37 * result + ( getScoreType() == null ? 0 : this.getScoreType().hashCode() );
         return result;
   }   


}


