package ltudjava.hcb.bt2.dto;
// Generated Aug 18, 2019 10:56:04 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Score generated by hbm2java
 */
@Entity
@Table(name="score"
    ,catalog="scoremanagement"
    , uniqueConstraints = @UniqueConstraint(columnNames={"student_id", "subject_id", "grade_id"}) 
)
public class Score  implements java.io.Serializable {


     private Integer id;
     private String studentId;
     private String subjectId;
     private int gradeId;
     private Float scodeHaft;
     private Float scoreFull;
     private Float scoreAnother;
     private Float scoreSummary;

    public Score() {
    }

	
    public Score(String studentId, String subjectId, int gradeId) {
        this.studentId = studentId;
        this.subjectId = subjectId;
        this.gradeId = gradeId;
    }
    public Score(String studentId, String subjectId, int gradeId, Float scodeHaft, Float scoreFull, Float scoreAnother, Float scoreSummary) {
       this.studentId = studentId;
       this.subjectId = subjectId;
       this.gradeId = gradeId;
       this.scodeHaft = scodeHaft;
       this.scoreFull = scoreFull;
       this.scoreAnother = scoreAnother;
       this.scoreSummary = scoreSummary;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="student_id", nullable=false, length=8)
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="subject_id", nullable=false, length=8)
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }

    
    @Column(name="grade_id", nullable=false)
    public int getGradeId() {
        return this.gradeId;
    }
    
    public void setGradeId(int gradeId) {
        this.gradeId = gradeId;
    }

    
    @Column(name="scode_haft", precision=12, scale=0)
    public Float getScodeHaft() {
        return this.scodeHaft;
    }
    
    public void setScodeHaft(Float scodeHaft) {
        this.scodeHaft = scodeHaft;
    }

    
    @Column(name="score_full", precision=12, scale=0)
    public Float getScoreFull() {
        return this.scoreFull;
    }
    
    public void setScoreFull(Float scoreFull) {
        this.scoreFull = scoreFull;
    }

    
    @Column(name="score_another", precision=12, scale=0)
    public Float getScoreAnother() {
        return this.scoreAnother;
    }
    
    public void setScoreAnother(Float scoreAnother) {
        this.scoreAnother = scoreAnother;
    }

    
    @Column(name="score_summary", precision=12, scale=0)
    public Float getScoreSummary() {
        return this.scoreSummary;
    }
    
    public void setScoreSummary(Float scoreSummary) {
        this.scoreSummary = scoreSummary;
    }




}


