package ltudjava.hcb.bt2.dto;
// Generated Aug 18, 2019 10:56:04 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name="subject"
    ,catalog="scoremanagement"
)
public class Subject  implements java.io.Serializable {


     private String code;
     private String name;

    public Subject() {
    }

    public Subject(String code, String name) {
       this.code = code;
       this.name = name;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false, length=8)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


