package ltudjava.hcb.bt2.dto;
// Generated Aug 16, 2019 10:26:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name="subject"
    ,catalog="scoremanagement"
)
public class Subject  implements java.io.Serializable {


     private String code;
     private String name;
     private Set<TimeTable> timeTables = new HashSet<TimeTable>(0);

    public Subject() {
    }

	
    public Subject(String code, String name) {
        this.code = code;
        this.name = name;
    }
    public Subject(String code, String name, Set<TimeTable> timeTables) {
       this.code = code;
       this.name = name;
       this.timeTables = timeTables;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false, length=8)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subject")
    public Set<TimeTable> getTimeTables() {
        return this.timeTables;
    }
    
    public void setTimeTables(Set<TimeTable> timeTables) {
        this.timeTables = timeTables;
    }




}


