package ltudjava.hcb.bt2.dto;
// Generated Aug 16, 2019 10:26:47 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TimeTableId generated by hbm2java
 */
@Embeddable
public class TimeTableId  implements java.io.Serializable {


     private String subjectCode;
     private int grade;

    public TimeTableId() {
    }

    public TimeTableId(String subjectCode, int grade) {
       this.subjectCode = subjectCode;
       this.grade = grade;
    }
   


    @Column(name="subject_code", nullable=false, length=8)
    public String getSubjectCode() {
        return this.subjectCode;
    }
    
    public void setSubjectCode(String subjectCode) {
        this.subjectCode = subjectCode;
    }


    @Column(name="grade", nullable=false)
    public int getGrade() {
        return this.grade;
    }
    
    public void setGrade(int grade) {
        this.grade = grade;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TimeTableId) ) return false;
		 TimeTableId castOther = ( TimeTableId ) other; 
         
		 return ( (this.getSubjectCode()==castOther.getSubjectCode()) || ( this.getSubjectCode()!=null && castOther.getSubjectCode()!=null && this.getSubjectCode().equals(castOther.getSubjectCode()) ) )
 && (this.getGrade()==castOther.getGrade());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSubjectCode() == null ? 0 : this.getSubjectCode().hashCode() );
         result = 37 * result + this.getGrade();
         return result;
   }   


}


