package ltudjava.hcb.bt2.dto;
// Generated Aug 18, 2019 10:56:04 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="scoremanagement"
)
public class User  implements java.io.Serializable {


     private String name;
     private String pass;
     private String nameshow;
     private String role;

    public User() {
    }

	
    public User(String name, String pass) {
        this.name = name;
        this.pass = pass;
    }
    public User(String name, String pass, String nameshow, String role) {
       this.name = name;
       this.pass = pass;
       this.nameshow = nameshow;
       this.role = role;
    }
   
     @Id 

    
    @Column(name="name", unique=true, nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="pass", nullable=false, length=64)
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }

    
    @Column(name="nameshow", length=64)
    public String getNameshow() {
        return this.nameshow;
    }
    
    public void setNameshow(String nameshow) {
        this.nameshow = nameshow;
    }

    
    @Column(name="role", length=32)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


