package ltudjava.hcb.bt2.dto;
// Generated Aug 15, 2019 11:16:22 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="scoremanagement"
)
public class User  implements java.io.Serializable {


     private String name;
     private Student student;
     private String pass;
     private String nameshow;

    public User() {
    }

	
    public User(Student student, String pass) {
        this.student = student;
        this.pass = pass;
    }
    public User(Student student, String pass, String nameshow) {
       this.student = student;
       this.pass = pass;
       this.nameshow = nameshow;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="student"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="name", unique=true, nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="pass", nullable=false, length=64)
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }

    
    @Column(name="nameshow", length=64)
    public String getNameshow() {
        return this.nameshow;
    }
    
    public void setNameshow(String nameshow) {
        this.nameshow = nameshow;
    }




}


